### PR TITLE
Remove dead code and further lower gas usage

### PR DESCRIPTION
**Pull request by geohot**

### CODE REVIEW

**Comment by K-Ho** [comment]
https://github.com/ethereum-optimism/synthetix/tree/geohot/safetycheck <-- in order to re-generate the JSON files, run `node publish build --use-OVM --show-warnings`. 
To change solc version used: https://github.com/ethereum-optimism/synthetix/blob/1623ed7133fb5d864bbccd6beb8f68143ddf99a7/publish/src/solidity.js#L68

**Comment by geohot** [comment]
Still failing CI with "Focused tests are not allowed", not sure what this means. But yarn test in packages/contracts passes 21 tests on my machine.

**Comment by K-Ho** [comment]
> Still failing CI with "Focused tests are not allowed", not sure what this means. But yarn test in packages/contracts passes 21 tests on my machine.

Oh yeah, that's just because the safety checker tests are `.only`ed

**Comment by K-Ho** [comment]
Made a couple small updates to this branch: https://github.com/ethereum-optimism/optimism-monorepo/pull/211 - should make `EtherCollateral` safe now and `console.log` when encountering a non-whitelisted opcode

**Comment by geohot** [comment]
A quick claim of why 1.5 million will be very hard (50 gas per byte). Arguments are put on the stack with DUP or PUSH, so something like an LT, while only costing 3, really costs more like 9.

Exit compare (3*4+10=22 gas): dupx dupx gt push(addr) jumpi
Load (3*4=12 gas, currently 6 more for add): dupx mload push(0x00) byte
Shift compare (3*6+10=28 gas): push(1) dupx shl dupx and push(addr) jumpi
Inc pc (6 gas, currently 8 more for jump): push(1) add

Even with the absolute minimum in hardcoded asm, you are left with 22+12+28+6 = 68 gas. Pushes do help? And maybe maybe there's word stuff?

**Comment by geohot** [comment]
got 1432474, though like...eww

https://github.com/geohot/optimism-monorepo/commit/7e07a996dff5e661790ac0023b7af18c34b86308

**Comment by K-Ho** [comment]
> got 1432474 with some multibytish, though like...eww (also, it doesn't work as is*)
> 
> now 1349924 after using all 32 bytes, 1323483 with new call check and cleanup
> 
> [geohot@7e07a99](https://github.com/geohot/optimism-monorepo/commit/7e07a996dff5e661790ac0023b7af18c34b86308)
> 
> * Would require compiler change to call with: CALLER PUSH1 0x0 SWAP1 GAS CALL. Or actually...question? What's "unsafe" about calling the execution manager with a value?

We need to make sure execution is deterministic on and off chain - the CALL opcode will fail if the call value exceeds its balance. You could have a call that failed on L2 but succeeds on L1 during a fraud proof (e.g. an attacker sends ETH to the contract right before execution).

**Comment by geohot** [comment]
Ahh I see. The fast version would require the compiler change than with the SWAP1 as far as I can think, since unless you track it, I don't think you can ever be sure you aren't in a PUSH.

**Comment by K-Ho** [comment]
> Ahh I see. The fast version would require the compiler change than with the SWAP1 as far as I can think, since unless you track it, I don't think you can ever be sure you aren't in a PUSH in O(1).
> 
> Also, do you need to be able to pass in an opcodeWhitelistMask, or can it be hardcoded?

Oooh! SWAP1 is a clever trick. Opcode whitelist mask could probably be hardcoded. As long as we can configure it without affecting audit/formal verification

**Comment by geohot** [comment]
Replaced by #214

**Pull request closed without merging**
