### PR TITLE
Adds `gas-profiler`

### PR DESCRIPTION
**Pull request by kfichter**
## Description
Hello! This PR introduces a new package, `gas-profiler`. `gas-profiler` is a utility for generating detailed profiles of contract executions. The package can either be used as an import or as a command-line application. More detailed information can be found in the package's `README.md`.

### Fixes
- Fixes [YAS-440](https://optimists.atlassian.net/browse/YAS-440)

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

**Comment by kfichter** [comment]
> This LGTM!! 

🎉🎉 

> I'll admit I didn't pour over this line by line, but one quick note is I don't see you do anything with `JUMPI` thought you do do some stuff with `JUMP`, idk if that would have any effect but worth calling out!

So what I'm doing with `JUMP` essentially just collects the gas usage during external contract calls and assigns it to the line corresponding to the final `JUMPDEST`. I don't think the Solidity compiler uses `JUMPI` for external calls (only internally for conditionals), so it's not necessary to carry out the same gas collection logic.

**Comment by kfichter** [comment]
> double LGTM! Very pretty code! Clearly there are linting issues but those are pretty trivial to fix. I'm sorry Kelvin but our current linting style doesn't use semi-colons 😁

Linting issues fixed!

**Comment by karlfloersch** [comment]
@kfichter looks like the build failed because of some missing dependency maybe? I wanna merge this once it passes CI!

**Comment by karlfloersch** [comment]
@kfichter looks like the build failed because of some missing dependency maybe? I wanna merge this once it passes CI!

**Comment by kfichter** [comment]
Weird, let me check this out

**Pull request merged**
