### PR TITLE
Bump version of toolchain and update dependencies

### PR DESCRIPTION
**Pull request by kfichter**
## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

**Review by karlfloersch — APPROVED** [review]
LGTM!

**Comment by karlfloersch** [comment]
@kfichter is this PR still relevant? We should update it & ship it if so

**Comment by kfichter** [comment]
I believe so, let's merge it

**Comment by tynes** [comment]
We deleted the ovm-toolchain

**Pull request closed without merging**
